// Generated by CoffeeScript 1.3.1
(function() {

  define(['views/content/list', 'views/main/login'], function(vContentList, vLogin) {
    return Backbone.Router.extend({
      routes: {
        "": "home",
        "login": "login"
      },
      home: function() {
        var home;
        home = new vContentList();
        return $('div#main').html(home.$el);
      },
      login: function() {
        return $('div#main').html(new vLogin().render().$el);
      }
    });
  });

}).call(this);
