// Generated by CoffeeScript 1.3.1
(function() {

  define(['views/content/list', 'views/main/login', 'views/main/selector'], function(vContentList, vLogin, vSelector) {
    return Backbone.Router.extend({
      routes: {
        "": "home",
        'all': 'all',
        "login": "login"
      },
      home: function() {
        var home;
        home = new vContentList();
        return $('div#main').html(home.$el);
      },
      all: function() {
        var all;
        all = new vContentList();
        return $('div#main').html(all.$el);
      },
      login: function() {
        return $('div#main').html(new vLogin().render().$el);
      }
    });
  });

}).call(this);
