// Generated by CoffeeScript 1.3.1
(function() {

  define(function(require) {
    var $, Backbone, MainRouter, ObjectRouter, vMenu, _;
    $ = require('jquery');
    _ = require('underscore');
    Backbone = require('backbone');
    vMenu = require('views/main/menu');
    MainRouter = require('routers/main');
    ObjectRouter = require('routers/object');
    return {
      initialize: function() {
        var mainRouter, objectRouter;
        $('header').html(new vMenu().render().$el);
        objectRouter = new ObjectRouter();
        mainRouter = new MainRouter();
        Backbone.View.prototype.navigate = function(loc) {
          return mainRouter.navigate(loc, true);
        };
        Backbone.history.start({
          pushState: true
        });
        $(document).on('click', 'a:not([data-bypass])', function(evt) {
          var href, protocol;
          href = $(this).attr('href');
          protocol = this.protocol + '//';
          if (href.slice(protocol.length !== protocol)) {
            evt.preventDefault();
            return mainRouter.navigate(href, true);
          }
        });
      }
    };
  });

}).call(this);
