// Generated by CoffeeScript 1.3.1
(function() {

  define(['collections/event', 'collections/link', 'collections/video', 'collections/document', 'collections/note'], function(cEvent, cLink, cVideo, cDocument, cNote) {
    return {
      'events': cEvent,
      'links': cLink,
      'videos': cVideo,
      'documents': cDocument,
      'notes': cNote
    };
  });

}).call(this);
