// Generated by CoffeeScript 1.3.1
(function() {

  define(['models/event', 'models/link', 'models/video', 'models/document', 'models/note'], function(mEvent, mLink, mVideo, mDocument, mNote) {
    return {
      'event': mEvent,
      'link': mLink,
      'video': mVideo,
      'document': mDocument,
      'note': mNote
    };
  });

}).call(this);
