// Generated by CoffeeScript 1.3.1
(function() {

  define(['text!../../../templates/event/listed', 'text!../../../templates/link/listed', 'text!../../../templates/video/listed', 'text!../../../templates/document/listed', 'text!../../../templates/note/listed'], function(tplListedEvent, tplListedLink, tplListedVideo, tplListedDocument, tplListedNote) {
    return {
      'event': tplListedEvent,
      'link': tplListedLink,
      'video': tplListedVideo,
      'document': tplListedDocument,
      'note': tplListedNote
    };
  });

}).call(this);
