// Generated by CoffeeScript 1.3.1
(function() {

  define(['text!../../../templates/event/full', 'text!../../../templates/link/full', 'text!../../../templates/video/full', 'text!../../../templates/document/full', 'text!../../../templates/note/full'], function(tplFullEvent, tplFullLink, tplFullVideo, tplFullDocument, tplFullNote) {
    return {
      'event': tplFullEvent,
      'link': tplFullLink,
      'video': tplFullVideo,
      'document': tplFullDocument,
      'note': tplFullNote
    };
  });

}).call(this);
