// Generated by CoffeeScript 1.3.1
(function() {

  define(['text!../../../templates/event/edit', 'text!../../../templates/link/edit', 'text!../../../templates/video/edit', 'text!../../../templates/document/edit', 'text!../../../templates/note/edit'], function(tplEvent, tplLink, tplVideo, tplDocument, tplNote) {
    return {
      'event': tplEvent,
      'link': tplLink,
      'video': tplVideo,
      'document': tplDocument,
      'note': tplNote
    };
  });

}).call(this);
