// Generated by CoffeeScript 1.3.1
(function() {

  define(['views/event/edit', 'views/link/edit', 'views/video/edit', 'views/document/edit', 'views/note/edit'], function(vEvent, vLink, vVideo, vDocument, vNote) {
    return {
      'event': vEvent,
      'link': vLink,
      'video': vVideo,
      'document': vDocument,
      'note': vNote
    };
  });

}).call(this);
