// Generated by CoffeeScript 1.3.1
(function() {

  define(['views/event/full', 'views/link/full', 'views/video/full', 'views/document/full', 'views/note/full'], function(vEventFull, vLinkFull, vVideoFull, vDocumentFull, vNoteFull) {
    return {
      'event': vEventFull,
      'link': vLinkFull,
      'video': vVideoFull,
      'document': vDocumentFull,
      'note': vNoteFull
    };
  });

}).call(this);
