// Generated by CoffeeScript 1.3.1
(function() {

  define(function(require) {
    var $, Backbone, vEditObject, vEditTags, _;
    $ = require('jquery');
    _ = require('underscore');
    Backbone = require('backbone');
    vEditObject = require('views/object/edit');
    vEditTags = require('views/tag/edit');
    return Backbone.View.extend({
      initialize: function() {
        return vEditObject.prototype.initialize.apply(this);
      },
      render: function() {
        var et;
        vEditObject.prototype.render.apply(this);
        et = new vEditTags({
          model: this.model
        });
        this.$('.tags-wrapper').append(et.render().$el);
        return this;
      }
    });
  });

}).call(this);
