// Generated by CoffeeScript 1.3.1
(function() {

  define(function(require) {
    var $, Backbone, vFullObject, vTagList, _;
    $ = require('jquery');
    _ = require('underscore');
    Backbone = require('backbone');
    vFullObject = require('views/object/full');
    vTagList = require('views/tag/list');
    return vFullObject.extend({
      render: function() {
        var tags, wrapper;
        vFullObject.prototype.render.apply(this);
        tags = new vTagList({
          tags: this.model.get('newtags')
        });
        wrapper = $('<div />').addClass('tags-wrapper');
        wrapper.html(tags.render().$el);
        this.$el.append(wrapper);
        return this;
      }
    });
  });

}).call(this);
