// Generated by CoffeeScript 1.3.1
(function() {

  define(function(require) {
    var $, Backbone, ListedTemplates, tplListedContent, _;
    $ = require('jquery');
    _ = require('underscore');
    Backbone = require('backbone');
    ListedTemplates = require('switchers/templates.listed');
    tplListedContent = require('text!../../../templates/content/listed');
    return Backbone.View.extend({
      render: function() {
        var tpl, tplRendered;
        this.$el.html(_.template(tplListedContent, {
          type: this.model.get('type')
        }));
        tpl = ListedTemplates[this.model.get('type')];
        tplRendered = _.template(tpl, this.model.toJSON());
        this.$('.content-body').html(tplRendered);
        return this;
      }
    });
  });

}).call(this);
