// Generated by CoffeeScript 1.3.1
(function() {

  define(['underscore', 'backbone', 'collections/tag', 'models/object'], function(_, Backbone, TagCollection, mObject) {
    return mObject.extend({
      defaults: _.extend({}, mObject.prototype.defaults, {
        'newtags': []
      }),
      set: function(attributes, options) {
        if (attributes.newtags !== void 0 && !(attributes.newtags instanceof TagCollection)) {
          attributes.newtags = new TagCollection(attributes.newtags);
        }
        return mObject.prototype.set.call(this, attributes, options);
      }
    });
  });

}).call(this);
