// Generated by CoffeeScript 1.3.1
(function() {

  define(['underscore', 'backbone', 'models/content'], function(_, Backbone, mContent) {
    return mContent.extend({
      urlRoot: '/api/document',
      defaults: _.extend({}, mContent.prototype.defaults, {
        'type': 'document',
        'filename': '',
        'filesize': 0,
        'title': '',
        'author': '',
        'pages': 0
      }),
      set: function(attributes, options) {
        return mContent.prototype.set.call(this, attributes, options);
      }
    });
  });

}).call(this);
