// Generated by CoffeeScript 1.3.1
(function() {

  define(['jquery', 'underscore', 'backbone', 'views/content/edit'], function($, _, Backbone, vEditContent) {
    var _this = this;
    return vEditContent.extend({
      events: _.extend({}, vEditContent.prototype.events, {
        'change .upload': 'onDocumentSelected'
      }),
      onDocumentSelected: function(e) {
        var file, updateProgressbar, xhr,
          _this = this;
        file = document.getElementById('pdf-file').files[0];
        xhr = new XMLHttpRequest();
        updateProgressbar = function(e) {
          _this.$('#progressbar').attr('value', e.loaded / e.total * 100);
        };
        xhr.upload.addEventListener('loadstart', this.showPart2, false);
        xhr.upload.addEventListener('progress', updateProgressbar(e), false);
        xhr.upload.addEventListener('load', this.onLoad, false);
        xhr.open('POST', '/api/upload_document.php', true);
        xhr.setRequestHeader('Content-type', file.type);
        xhr.setRequestHeader('X_FILE_NAME', file.name);
        xhr.setRequestHeader('X_FILE_SIZE', file.size);
        xhr.send(file);
        return xhr.onreadystatechange = function() {
          var response;
          if (xhr.readyState === 4) {
            if (xhr.status === 200) {
              response = JSON.parse(xhr.responseText);
              _this.model.set(response);
              _this.render();
              _this.showPart3;
            }
          }
        };
      },
      initialize: function() {
        return vEditContent.prototype.initialize.apply(this);
      },
      render: function() {
        vEditContent.prototype.render.apply(this);
        if (this.model.get('id') != null) {
          this.showPart3();
        } else {
          this.showPart1();
        }
        return this;
      },
      showPart1: function() {
        _this.$('#part1').show();
        _this.$('#part2').hide();
        _this.$('#part3').hide();
      },
      showPart2: function() {
        _this.$('#part1').hide();
        _this.$('#part2').show();
        _this.$('#part3').hide();
      },
      showPart3: function() {
        _this.$('#part1').hide();
        _this.$('#part2').hide();
        _this.$('#part3').show();
      }
    });
  });

}).call(this);
