// Generated by CoffeeScript 1.3.1
(function() {

  define(['backbone', 'views/content/full'], function(Backbone, vFullContent) {
    return vFullContent.extend({
      render: function() {
        vFullContent.prototype.render.apply(this);
        return this;
      }
    });
  });

}).call(this);
