// Generated by CoffeeScript 1.3.1
(function() {

  define(['jquery', 'underscore', 'backbone', 'text!../../../templates/main/menu'], function($, _, Backbone, tplMenu) {
    return Backbone.View.extend({
      tagName: 'nav',
      id: 'main',
      events: {
        "click #logout": "logout"
      },
      logout: function() {
        var _this = this;
        return $.post('/api/logout').error(function(response) {
          if (response.status === 401) {
            _this.navigate('login');
          }
        });
      },
      render: function() {
        this.$el.html(_.template(tplMenu));
        return this;
      }
    });
  });

}).call(this);
