// Generated by CoffeeScript 1.3.1
(function() {

  define(['text!../../../templates/main/selector'], function(tpl) {
    return Backbone.View.extend({
      id: 'selector',
      filtered: {},
      events: {
        "change #selector ul li": "onContentSelected"
      },
      onContentSelected: function(e) {
        var checkboxes, coll, tags,
          _this = this;
        console.log(e);
        checkboxes = $('#selector ul li input:checked');
        coll = [];
        this.collection.reset();
        _.each(checkboxes, function(checkbox) {
          return coll = _.union(_this.base_collection.where({
            type: checkbox.id
          }), coll);
        });
        this.collection.reset(coll);
        tags = {};
        this.base_collection.each(function(model) {
          return model.get('newtags').each(function(tag) {
            var t;
            t = tag.get('slug');
            if (_.has(tags, t)) {
              return tags[t] = tags[t] + 1;
            } else {
              return tags[t] = 1;
            }
          });
        });
      },
      initialize: function() {
        this.base_collection = this.options.base_collection;
        return this.collection.comparator = function(model) {
          var m;
          m = parseInt(model.get('created').replace(/[- :]/g, ""));
          return -m;
        };
      },
      render: function() {
        this.$el.html(_.template(tpl));
        return $('#sidebar').html(this.$el);
      }
    });
  });

}).call(this);
